name: Docker

on: [push, pull_request]
#   push:
#     branches:
#       - master
#       - 'v[0-9]+*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zbeekman/ShellCheck-Linter-Action@v1.0.1
      - name: Install Bats
        run: |
          curl -sSL -o /tmp/bats_v0.4.0.tar.gz https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
          tar -xf /tmp/bats_v0.4.0.tar.gz
          sudo bats-0.4.0/install.sh /usr/local
      - run: ./scripts/docker.sh build
      - run: ./scripts/docker.sh test

  publish:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/v'))
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.ref }} =~ ^refs/heads/(master|v[0-9]+\.[0-9]+.*)$ ]]; then
              echo ::set-output name=match::true
          fi  # See: https://stackoverflow.com/a/58869470/1123955
      - name: Is A Publish Branch
        if: steps.check-branch.outputs.match == 'true'
        run: curl -X POST -d '{"from":"GitHub Action"}' "$DOCKER_REBUILD_URL"
        env:
          DOCKER_REBUILD_URL: ${{ secrets.DOCKER_REBUILD_URL }}
      - name: Is Not A Publish Branch
        if: steps.check-branch.outputs.match != 'true'
        run: echo 'Not A Publish Branch'
